#!/bin/sh

CURL=curl
PORT=443

CMDNAME=$(basename $0)

CURRENT=$(cd $(dirname $0);pwd)

if [ -z $JWT_USER_PATH ]; then
  USER_ID=`id -u`
  DOWNLOAD_FOLDER=/tmp/jwt_user_u$USER_ID
  DOWNLOAD_PATH="${DOWNLOAD_FOLDER}/token.jwt"
else
  DOWNLOAD_PATH=$JWT_USER_PATH
fi
umask 077; mkdir -p `dirname $DOWNLOAD_PATH`

if [ -n $JWT_SERVER_URL ]; then
  URL=$JWT_SERVER_URL
fi

if [ -n $LOGNAME ]; then
  ACCOUNT=$LOGNAME
fi

while getopts s:l:p:f OPT
do
  case $OPT in
    "s" ) URL="$OPTARG" ;;
    "l" ) ACCOUNT="$OPTARG" ;;
    "p" ) PORT="$OPTARG" ;;
    "f" ) FOREGROUND=true ;;
    * ) echo "Usage: $CMDNAME [-s URL] [-l USER] [-f]" 1>&2
          exit 1 ;;
  esac
done

if [ -z "$URL" -o -z "$ACCOUNT" ]; then
 echo "Usage: $CMDNAME [-s URL] [-l USER] [-f]" 1>&2
 exit 1
fi

if [ -t 0 ]; then
  echo -n "Passphrase: "
  trap "stty echo" HUP INT QUIT TERM
  stty -echo
  read PASS
  stty echo

  echo
else
  read PASS
fi

if [ -z "$FOREGROUND" ]; then
    echo "$PASS" | $CURRENT/jwt-agent-core -s $URL -l $ACCOUNT &
else
    echo "$PASS" | $CURRENT/jwt-agent-core -s $URL -l $ACCOUNT
fi
